### ISSUE TITLE
Error with psite predict `-i` flag

### ISSUE THREAD

**Issue by ericmalekos** [gxelab/psite#4]
When I try to train the model with `-i` flag set to ignore tx version it crashes, but when I remove it, it runs fine. Just flagging this as a potential bug and to ask if I should be concerned about the output

```
psite train -i gencode.v46_onGCA.fa SRR15513148_Aligned.toTranscriptome.out.bam SRR1
5513148_transcriptome.train gencode.v46_onGCA.info
Traceback (most recent call last):
  File "/gstore/home/malekose/micromamba/envs/test/bin/psite", line 8, in <module>
    sys.exit(psite())
  File "/gstore/home/malekose/micromamba/envs/test/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/gstore/home/malekose/micromamba/envs/test/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/gstore/home/malekose/micromamba/envs/test/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/gstore/home/malekose/micromamba/envs/test/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/gstore/home/malekose/micromamba/envs/test/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/gstore/home/malekose/micromamba/envs/test/lib/python3.10/site-packages/psite/train.py", line 250, in train
    ax = qwidth_freq.plot(kind='bar')
  File "/gstore/home/malekose/micromamba/envs/test/lib/python3.10/site-packages/pandas/plotting/_core.py", line 1030, in __call__
    return plot_backend.plot(data, kind=kind, **kwargs)
  File "/gstore/home/malekose/micromamba/envs/test/lib/python3.10/site-packages/pandas/plotting/_matplotlib/__init__.py", line 71, in plot
    plot_obj.generate()
  File "/gstore/home/malekose/micromamba/envs/test/lib/python3.10/site-packages/pandas/plotting/_matplotlib/core.py", line 508, in generate
    self._post_plot_logic(ax, self.data)
  File "/gstore/home/malekose/micromamba/envs/test/lib/python3.10/site-packages/pandas/plotting/_matplotlib/core.py", line 1966, in _post_plot_logic
    s_edge = self.ax_pos[0] - 0.25 + self.lim_offset
IndexError: index 0 is out of bounds for axis 0 with size 0

psite train gencode.v46_onGCA.fa SRR15513148_Aligned.toTranscriptome.out.bam SRR15513148_transcriptome.train gencode.v46_onGCA.info

 % ls -lah
-rw-r--r--  1 malekose idmgmt 436M Aug  7 16:06 gencode.v46_onGCA.fa
-rw-r--r--  1 malekose idmgmt  20M Aug  7 16:09 gencode.v46_onGCA.info
-rw-r--r--  1 malekose idmgmt 1.1G Aug  7 14:34 SRR15513148_Aligned.out.bam
-rw-r--r--  1 malekose idmgmt 2.8M Aug  7 14:34 SRR15513148_Aligned.out.bam.bai
-rw-r--r--  1 malekose idmgmt 3.1G Aug  7 14:25 SRR15513148_Aligned.toTranscriptome.out.bam
-rw-r--r--  1 malekose idmgmt  15M Aug  7 14:26 SRR15513148_Aligned.toTranscriptome.out.bam.bai
-rw-r--r--  1 malekose idmgmt  497 Aug  7 16:23 SRR15513148_transcriptome.train.dam.pickle
-rw-r--r--  1 malekose idmgmt 646K Aug  7 16:24 SRR15513148_transcriptome.train.gbt.pickle
-rw-r--r--  1 malekose idmgmt 2.2K Aug  7 16:26 SRR15513148_transcriptome.train.log
-rw-r--r--  1 malekose idmgmt  16K Aug  7 16:23 SRR15513148_transcriptome.train.offset_distribution.pdf
-rw-r--r--  1 malekose idmgmt 9.1K Aug  7 16:23 SRR15513148_transcriptome.train.qwidth_distribution.pdf
```

**Comment by mt1022** [comment]
Thanks for reporting. We'll try to figure out the cause of the crash recently.
