### ISSUE TITLE
Error with psite predict

### ISSUE THREAD

**Issue by ericmalekos** [gxelab/psite#5]
I am running into an issue where psite predict fails part way through from a ValueError. Any ideas on how to proceed or what the problem might be?

```
psite predict gencode.v46_onGCA.fa SRR15513148_Aligned.toTranscriptome.out.bam SRR15513148_transcriptome.train.gbt.pickle trained_SRR15513148_Aligned.out.bam
...load ref and model
...Parse bam by chunk and predict
^[[ATraceback (most recent call last):
  File "/gstore/home/malekose/micromamba/envs/test/bin/psite", line 8, in <module>
    sys.exit(psite())
  File "/gstore/home/malekose/micromamba/envs/test/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/gstore/home/malekose/micromamba/envs/test/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/gstore/home/malekose/micromamba/envs/test/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/gstore/home/malekose/micromamba/envs/test/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/gstore/home/malekose/micromamba/envs/test/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/gstore/home/malekose/micromamba/envs/test/lib/python3.10/site-packages/psite/predict.py", line 89, in predict
    p_sites = model.predict(batch)
  File "/gstore/home/malekose/micromamba/envs/test/lib/python3.10/site-packages/sklearn/ensemble/_gb.py", line 1611, in predict
    raw_predictions = self.decision_function(X)
  File "/gstore/home/malekose/micromamba/envs/test/lib/python3.10/site-packages/sklearn/ensemble/_gb.py", line 1564, in decision_function
    X = self._validate_data(
  File "/gstore/home/malekose/micromamba/envs/test/lib/python3.10/site-packages/sklearn/base.py", line 608, in _validate_data
    self._check_feature_names(X, reset=reset)
  File "/gstore/home/malekose/micromamba/envs/test/lib/python3.10/site-packages/sklearn/base.py", line 535, in _check_feature_names
    raise ValueError(message)
ValueError: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- s0_C
- s0_G
- s0_T
- s1_C
- s1_G
- ...
```

The output is generated for a while before the error and appears correct:
```
samtools view trained_SRR15513148_Aligned.out.bam | head -n4
SRR15513148.4648017     256     ENST00000488147.2       121     0       27M     *       0       0       CAGAAGGTCTCTGGAGACATCTTCAGC     AAAAAEEEEEEEEEEEEEEEEEEEEEE     NH:i:33 HI:i:16 PS:i:11
SRR15513148.8298314     256     ENST00000488147.2       121     0       27M     *       0       0       CAGAAGGTCTCTGGAGACATCTTCAGC     AA6AAEE/AEEEEEEE//A/EEEE/EE     NH:i:33 HI:i:16 PS:i:11
SRR15513148.6833577     256     ENST00000488147.2       121     0       27M     *       0       0       CAGAAGGTCTCTGGAGACATCTTCAGC     AAAAAEEEEEEEEEEEEEEEEEEEEEE     NH:i:33 HI:i:16 PS:i:11
SRR15513148.30150551    256     ENST00000488147.2       121     0       27M     *       0       0       CAGAAGGTCTCTGGAGACATCTTCAGC     AAAAAEEEEEEEEEEEEEEEEEEEEEE     NH:i:33 HI:i:16 PS:i:11
```

**Comment by mt1022** [comment]
I am not sure whether you specified a different number of flanking nucleotides for training. Can you share the command used for training? It would be better if you could provide the commands starting from the reads file and the reference genome/transcriptome for me to reproduce the error.

**Comment by ericmalekos** [comment]
Thank you, here are the commands

```
    STAR --genomeDir ${INDEX} \
         --readFilesIn ${READ} \
         --outFileNamePrefix ${OUTPUT_DIR}${NAME}_ \
         --outSAMtype BAM Unsorted \
         --quantMode GeneCounts TranscriptomeSAM \
         --outFilterMultimapNmax 100 \
         --winAnchorMultimapNmax 5000 \
         --runThreadN ${N} \
         --alignEndsType EndToEnd \
         --outSAMattributes All \
         --outFilterMatchNmin 16 \
         --outFilterMismatchNmax 2 \
         --outSAMprimaryFlag AllBestScore
```

I then removed all reads from the transcriptome bam that are not between 25 and 34 nts in length:

```
samtools view -h SRR15513148_Aligned.toTranscriptome.out.bam | awk '$0 ~ /^@/ || ($6 !~ /[ID]/ && length($10) >= 25 &&
length($10) <= 34)' | samtools view -b > filtered_SRR15513148_Aligned.toTranscriptome.out.bam
```

I made the info file with provided R script and trained with default parameters:
```
Rscript ./psite/scripts/extract_txinfo.R gencode.v46_onGCA.gtf gencode.v46_onGCA.info

psite train gencode.v46_onGCA.fa filtered_SRR15513148_Aligned.toTranscriptome.out.bam SRR15513148_transcriptome.train gencode.v46_onGCA.info
```

And same for predict:
```
psite predict gencode.v46_onGCA.fa filtered_SRR15513148_Aligned.toTranscriptome.out.bam SRR15513148_transcriptome.train.gbt.pickle trained_SRR15513148_Aligned.toTranscriptome.out.bam
```

**Comment by ericmalekos** [comment]
I have a strange finding to report - when I ran it, I noticed that it was failing on two specific entries, when I removed these transcripts from the bam file, psite predict ran to completion:

```
samtools view -h filtered_SRR15513148_Aligned.toTranscriptome.out.bam | grep -v "ENST00000363781.1" | grep -v "ENST00000364228.1" | samtools view -b > trim_filtered_SRR15513148_Aligned.toTranscriptome.out.bam

psite predict gencode.v46_onGCA.fa trim_filtered_SRR15513148_Aligned.toTranscriptome.out.bam SRR15513148_transcriptome.train.gbt.pickle trained_SRR15513148_Aligned.toTranscriptome.out.bam
```

**Comment by mt1022** [comment]
Hi, Eric,

I have tested PSite with GENCODE release 46 and the Ribo-Seq library SRR15513148. I have no problem running the `predict` module (issue associated with the `-i` parameter in the `train` module has been fixed). The complete steps are attached below. We have processed that library in a recent work so I used a clean version of the fastq file after trimming adapters and removing rRNAs & tRNAs in that work. Although I used all reads (PSite will determine most abundant read lengths automatically), I do not think that is the problem. Besides, I start with annotations downloaded directly from GENCODE, while it seems that you were using a custom annotation? (`_onGCA.fa`)

```bash
wget https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_46/GRCh38.primary_assembly.genome.fa.gz
wget https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_46/gencode.v46.annotation.gtf.gz
wget https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_46/gencode.v46.transcripts.fa.gz

gunzip gencode.v46.annotation.gtf.gz
gunzip GRCh38.primary_assembly.genome.fa.gz
gunzip gencode.v46.transcripts.fa.gz

STAR --runThreadN 8 --runMode genomeGenerate --genomeDir STAR --genomeFastaFiles GRCh38.primary_assembly.genome.fa --sjdbGTFfile gencode.v46.annotation.gtf --sjdbOverhang 100

Rscript --vanilla extract_txinfo.R gencode.v46.annotation.gtf gencode.v46.annotation.gtf.txinfo

sed 's/|.*//' gencode.v46.transcripts.fa >gencode.v46.transcripts.fixname.fa

STAR --outFilterType BySJout --runThreadN 8 --outFilterMismatchNmax 2 --genomeDir STAR --readFilesIn SRR15513148.trim.clean.fq.gz --readFilesCommand zcat --outFileNamePrefix SRR15513148_ --outSAMattributes All --outSAMtype BAM SortedByCoordinate --quantMode TranscriptomeSAM --outFilterMultimapNmax 1 --outFilterMatchNmin 16 --alignEndsType EndToEnd

psite train gencode.v46.transcripts.fixname.fa SRR15513148_Aligned.toTranscriptome.out.bam SRR15513148_transcriptome.train gencode.v46.annotation.gtf.txinfo

psite predict gencode.v46.transcripts.fixname.fa SRR15513148_Aligned.toTranscriptome.out.bam SRR15513148_transcriptome.train.gbt.pickle SRR15513148_Aligned.toTranscriptome.psite.bam
```
